language: d

#compiler:
#  - dmd

notifications:
  email: false

env:
  global:
    - secure: "kFhU+DZjhq/KbDt0DIDWnlskXMa12miNelmhhy30fQGgVIdiibDGKMNGyLahWp8CnPu1DARb5AZWK2TDfARdnURT2pgcsG83M7bYIY6cR647BWjL7oAhJ6CYEzTWJTBjeUjpN/o4vIgfXSDR0c7vboDi7Xz8ilfrBujPL2Oi/og="

install:
  # dmd
  # dub
  - DMD_VER=2.066.1
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.21
  - DUB=dub-${DUB_VER}-linux-x86_64
  #- sudo apt-get install libev-dev
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz

script:
  - dub test
  - ./push-ddoc.sh
